public class MyUseCase extends UseCase<String, String> {

    @Override
    protected void onRun(String parameters) {
        // Do stuff
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // Finish doing stuff
        notifySuccess("Yeso!!");
    }

}
